# Generated by Django 6.0.2 on 2026-02-27 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('schema_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Namespaced config key, e.g. 'feature_flags.dark_mode'.", max_length=255)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], default='development', max_length=20)),
                ('data', models.JSONField(help_text='Configuration value stored as JSONB.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_entries', to='organizations.organization')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='schema_registry.configschema')),
            ],
            options={
                'verbose_name': 'Config Entry',
                'verbose_name_plural': 'Config Entries',
                'ordering': ['organization', 'key', 'environment'],
                'unique_together': {('organization', 'key', 'environment')},
            },
        ),
    ]
