# Generated by Django 6.0.2 on 2026-02-27 12:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfigSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(help_text='Semantic version of this schema (MAJOR.MINOR.PATCH). Must match the regex ^\\d+\\.\\d+\\.\\d+$.', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_semver', message='schema_version must follow semantic versioning: "MAJOR.MINOR.PATCH" (e.g. 1.0.0, 2.3.14).  Only digits and dots are allowed.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('schema_definition', models.JSONField(help_text='JSON Schema definition conforming to the namespaces contract. Validated by SchemaValidator before every save.')),
                ('is_active', models.BooleanField(default=False, help_text='Marks this schema as the active system configuration schema. Only one row may be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Config Schema',
                'verbose_name_plural': 'Global Config Schemas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_schema', violation_error_message='Another GlobalConfigSchema is already active. Deactivate it before activating a new one.')],
            },
        ),
        migrations.CreateModel(
            name='ConfigSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('schema_definition', models.JSONField(help_text='Full JSON Schema document stored as JSONB.')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Config Schema',
                'verbose_name_plural': 'Config Schemas',
                'ordering': ['organization', 'name', '-version'],
                'unique_together': {('organization', 'name', 'version')},
            },
        ),
    ]
