# Generated by Django 6.0.2 on 2026-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier auto-generated from the organisation name.', max_length=255, unique=True)),
                ('config_overrides', models.JSONField(blank=True, default=dict, help_text='Org-level overrides applied on top of the active GlobalConfigSchema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['id'],
            },
        ),
    ]
