# Generated by Django 5.0.6 on 2026-03-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='effective_config',
            field=models.JSONField(blank=True, default=None, help_text='Last-computed effective configuration (schema defaults + org overrides). Null if never computed or if stored overrides are stale under the current schema.', null=True),
        ),
    ]
